---
- hosts: container
  user: root
#  gather_facts: no
  tasks:
  - name: start exited docker
    shell: docker start $(docker ps -a | grep Exited | awk '{print $1}')
 # - name: install python-pip package
 #   apt: name={{ item }} state=present force=yes
 #   with_items:
 #     - python-pip

 # - name: pip install docker-py
 #   pip:
 #     name: "{{ item }}"
 #   with_items:
 #     - docker-py

 # - name: 获取到exited容器的id并注册为result
 #   shell: docker ps -aq -f status=exited
 #   register: result

 # - name: 通过result输出id启动 exited 的容器
 #   docker_container:
 #     name: "{{ item }}"
 #     state: started
 #   with_items:
 #     - "{{ result.stdout_lines }}"
 #   tags:
 #     - start
